tutorial/account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView

from django.urls import reverse_lazy

app_name = 'account'
urlpatterns = [
    url(r'^$', views.home),
    url(r'^login/$', LoginView.as_view(template_name='account/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='account/logout.html'), name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='profile'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),

    url(r'^reset-password/$',PasswordResetView.as_view(
        template_name='account/reset_password.html',
        success_url=reverse_lazy('account:reset_password_done'),
        email_template_name='account/reset_password_email.html'
        ),name='reset_password'),

    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('account:reset_password_complete'), #(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/
    ), name='reset_password_confirm'),
    url(r'^reset-password/complete/$',PasswordResetCompleteView.as_view(template_name='account/reset_password_complete.html'),name='reset_password_complete'),
    url(r'^reset-password/done/$',PasswordResetDoneView.as_view(template_name='account/reset_password_done.html'),name='reset_password_done'),
]

tutorial/tutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from tutorial import views

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]
urlpatterns = [
    url(r'^$', views.login_redirect, name='login_redirect'),
    url('admin/', admin.site.urls),
    url(r'^account/', include ('account.urls', namespace='account')),
]

tutorial/account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, blank=True, default='')
    city = models.CharField(max_length=100, blank=True, default='')
    website = models.URLField(blank=True, default='')
    phone = models.IntegerField(default=0, blank=True)

def create_profile(sender,**kwargs ):
    if kwargs['created']:
        user_profile=UserProfile(user=kwargs['instance'])
        user_profile.save()

post_save.connect(create_profile, sender=User)

tutorial/account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
        )

tutorial/account/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm
from account.forms import RegistrationForm, EditProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

# Create your views here.

def home(request):
    numbers = [1,2,3,4,5]
    name = 'DevOps'

    args = {'myName': name ,'number': numbers}
    return render(request, 'account/home.html',  args)

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/account/')
    else:
        form = RegistrationForm()

        args = {'form':form}
        return render(request, 'account/reg_form.html', args)


def view_profile(request):
    args = {'user':request.user}
    return render(request, 'account/profile.html', args)

# @login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('/account/profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'account/edit_profile.html', args)   

# @login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/account/profile')
        else:
            return redirect('/account/change-password')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'account/change_password.html', args)    

tutorial/tutorial/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('/account/login')

tutorial/account/templates/base.html
<html>
    <head>
        <base href="/"> <!--Fix lỗi hiển thị html sau đường dẫn tiếp theo "/"-->
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> -->
        <link href="../static/account/css/bootstrap.min.css" rel="stylesheet">
        <link href="../static/account/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
        <link href="../static/account/css/navbar.css" rel="stylesheet">
        <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/navbar/">
        <script src="../static/account/js/bootstrap.min.js"></script>
        <script src="../static/account/js/ie-emulation-modes-warning.js"></script>
        <script src="../static/account/js/ie10-viewport-bug-workaround.js"></script>
        <script src="../static/account/js/jquery-1.12.4.min.js"></script>
        {% block head %}
        <meta charset="utf-8">
        <title>Base</title>
        {% endblock %}
    </head>
    <body>
        <div class="container">
            <!-- Static navbar -->
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="/">Social Network</a>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        {% if user.is_authenticated %}
                        <ul class="nav navbar-nav">
                            <li><a href="/account">Home</a></li>
                            <li><a href="/account/logout">Logout</a></li>
                            <li><a href="{% url 'account:profile' %}">Profile</a></li>
                            <li><a href="/account/profile/edit">Edit Profile</a></li>
                            <li><a href="/account/change-password">Change Password</a></li>
                            <li><a href="/account/reset-password">Reset Password</a></li>
                            <li><a href="/account/reset-password/done">Password Done</a></li>
                        </ul>  
                        {% else %}
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="/account/login">Login</a></li>
                            <li><a href="account/register">Register</a></li>
                        </ul>
                        {% endif %}
                    </div><!--/.nav-collapse -->
                </div><!--/.container-fluid -->
            </nav>
        </div> <!-- /container -->
        {% block body%}
        <h1>Base</h1>
        {% endblock %}
    </body>

</html>